default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: furima_38584_development

  <<: *default
  database: furima_38584_test


production:
  <<: *default
  database: furima_38584_production
  username: furima_38584
  password: <%= ENV['FURIMA_38584_DATABASE_PASSWORD'] %>